### PR TITLE
[Bug] Fixing wrong request variable

### PR DESCRIPTION
**Pull request by fopina**

### CODE REVIEW

**Comment by Mzack9999** [comment]
@fopina Nice catch! Thanks!

**Review by Mzack9999 — APPROVED** [review]

**Comment by fopinappb** [comment]
still couldn't get it to work (or your httpx redirect chain branch) due to `context canceled` 😞 
ended up going with something simpler like https://github.com/fopinappb/httpx/commit/533f0c8f3d77488919404b04feeba1685e8b70f6 as I only needed the final URL, not the full chain

**Comment by Mzack9999** [comment]
@fopina would it be possible to provide more details on how to reproduce the unexpected behavior?

**Comment by fopinappb** [comment]
@Mzack9999 sorry for replying from different handle as I only have the work laptop at the moment :)

```
➜  httpx git:(feature-redirect-chain) echo 34.255.125.142 | go run cmd/httpx/httpx.go -json -follow-redirects -silent -o x
➜  httpx git:(feature-redirect-chain) ✗ cat x
➜  httpx git:(feature-redirect-chain) ✗
```

expected to see these
```
➜  httpx git:(feature-redirect-chain) ✗ curl -vkL https://34.255.125.142 |& grep -i location:
< Location: https://accounts.ref.o2.co.uk/
< location: https://identity.ref.o2.co.uk/auth?proof_requirement_id=00af3806-2425-4514-b0ae-3ee5fa45a043&sendTo=https%3A%2F%2Faccounts.ref.o2.co.uk%2F%3Fcheckproduct%3Dtrue&failureUrl=https%3A%2F%2Faccounts.ref.o2.co.uk%2F
< Location: http://identity.ref.o2.co.uk/http_msisdn_forward_redirect?msisdn_forward_request_id=7b1f4207-2ca5-4ffe-b94d-e36a27f9a78c
< Location: https://identity.ref.o2.co.uk/auth/msisdn_forward?msisdn_forward_request_id=7b1f4207-2ca5-4ffe-b94d-e36a27f9a78c
< Location: https://identity.ref.o2.co.uk/errors
```

there's just no output at all. but it's probably something simple missing, I just haven't debugged anything yet

**Comment by Mzack9999** [comment]
@fopina Thanks for the very detailed explanation! Hopefully this should be finally fixed in https://github.com/projectdiscovery/httpx/pull/251

**Comment by fopinappb** [comment]
retested and working inded thanks! 👍 
wondering why you decided to concatenate all response headers in single string (instead of array) unlike status-codes

**Comment by Mzack9999** [comment]
@fopinappb the request/response are the output of the standard library functions `httputil.DumpRequest` and `httputil.DumpResponse`, that returns a bytes slice. Do you think it may be useful to have for example headers parsed and exposed, in a structure like the following one:

```
type ChainItem struct {
	Request    []byte
	RequestHeaders    map[string]string
	Response   []byte
	ResponseHeaders    map[string]string
	StatusCode int
}
```

**Comment by fopina** [comment]
Yes, it’s the direct dump of each request/response in the chain but maybe it’d make sense to not merge them all into a single string and keep them separate in an array, like chain-status-codes. Also good for consistency I think.
Splitting the headers as well would definitely be useful in my use case but I think it’s unnecessary burden for nuclei (every CPU hates string operations!) as might not be useful for most cases. And it’s easy enough to iterate over lines, for those consuming the output

**Pull request merged**
